[package]
name = "Quadcopter"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"
rtic = { version = "2", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "2", features = ["cortex-m-systick"] }
stm32f4xx-hal = { version = "0.21", features = ["stm32f411"] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0"
embedded-alloc = "0.7.0"

[package.metadata.dfu]
chip = "STM32F411CEUx"
protocol = 2

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[[bin]]
name = "Quadcopter"
path = "src/main.rs"
test = false
bench = false
